### PR TITLE
Signup page clone

### PR DESCRIPTION
**Pull request by rgcavalheiro**
Signup page may as specified.

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work, team! 🖥️ 👀 ✨ 
## However, some changes are still required... 🧰 🔨 🔧 

- Your version is missing the top section as well as the sign-up button on the top-right corner. Please clone this section from the original page.

| Your version | Original page |
| --- | --- |
| image | image |

- Please use a more descriptive Pull Request message. You may summarize the things you learned by building this project here.

- Please use semantic HTML tags, such as `<nav>`, `<main>` and `<footer>` to section your code.

**[OPTIONAL]**

- Use a `font-family` and text size that better resemble the original page.

### Submit these changes and request a new code review! 😄 👍 
### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Review by expjazz — CHANGES_REQUESTED** [review]
## Status: Changes Required :red_circle: 

### You did a great job in this project :clap: 

#### However, there are still a few aspects that we need to improve in order to get this project approved:

- [x]  It appears that you did not set up your linters in the right way. Please refer to [this](https://github.com/microverseinc/linters-config/tree/master/html-css) page to checkout how to set them locally. For the github actions, you linters.yml should look like [this](https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml)

- [x] The signup button should be a little bit more up and to the left.

| Yours | Original |
|:---:|:---:|
| image | screencapture-accounts-intuit-com-signup-html-1594665050515 |

### Please submit for a new review after these changes are made :pray: 

Good Luck and Happy Coding

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

**Review by expjazz — CHANGES_REQUESTED** [review]
## Project Status: Changes Requested :red_circle: 

#### The project looks ready, and you made all the necessary adjustments, with only one detail missing: 

- [x]  The linter (there are linter errors).

Kindly fix that and submit again so we can approve this project :+1: 

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

**Review by expjazz — APPROVED** [review]
## Status: Project Approved :green_circle: 

#### You did great on this project :clap: 

For the next ones, consider being more descriptive in the Pull Request (it is always a good practice to do so).

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

**Pull request merged**
